### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by pronebird** [MazeMap/Leaflet.TileLayer.PouchDBCached#27] opened 2017-02-23 18:15 UTC
Module does not expose any methods and modifies some global L object. Impossible to use in modern projects.

**Comment by IvanSanchez** [comment] 2017-02-23 18:21
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.

In particular, the title is not descriptive enough, and there is no reproducible case where using this Leaflet plugin fails to build/bundle.

**Closed as completed by IvanSanchez** 2017-02-23 18:21 UTC
