### ISSUE TITLE
Does it work with mapbox maps?

### ISSUE THREAD

**Issue by etcware** [MazeMap/Leaflet.TileLayer.PouchDBCached#17] opened 2016-04-01 08:36 UTC
I tried to integrate the library with mapbox but it doesn't seem to work.
To start I don't cached any tiles and my expectation is that it gets tiles from server but the map is incomplete.

**Comment by IvanSanchez** [comment] 2017-01-16 09:39
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by robindierckx** [comment] 2017-03-07 13:11
For me it is working with mapbox

**Comment by IvanSanchez** [comment] 2017-03-07 14:06
Unable to reproduce → closing.

**Closed as completed by IvanSanchez** 2017-03-07 14:06 UTC
Labels: need more info
